In [1]:
import numpy as np

In [3]:
#listeleri hatırlayalım 
mylist=[1,2,3]

In [4]:
#liste tipi
type(mylist)

list

In [6]:
#listeyi array yapma
myarray=np.array(mylist)

In [8]:
myarray

array([1, 2, 3])

In [9]:
type(myarray)

numpy.ndarray

In [11]:
#0 dan 10 a kadar yazdır
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#0 dan 10 a kadar 2 şer 2 şer yazdır
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
#5,5 lik 0 matrisi oluştur
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
#10,5 lik 0 matrisi oluştur
np.zeros(shape=(10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
#2,4 lük 1 matrisi oluştur
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
#3,3 lük 1 matrisi oluştur
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
#0 ile 100 arasında random sayılarla oluşan bir array oluştur
np.random.randint(0,100,10)


array([26, 43, 70, 10, 71, 17, 86, 15, 24, 56])

In [24]:
random= np.random.randint(0,100,10)
print(random)

[ 0 42 91 19 73 88 79 27 43 38]


In [28]:
#olusturduğum array içerisindeki max ve min değerlerini bulalim
print(random.max())
print(random.min())

91
0


In [29]:
#max ve min değeri kaçıncı satirda
print(random.argmax())
print(random.argmin())

2
0


In [30]:
#ortalama değeri bul
print(random.mean())


50.0


In [32]:
#array boyutu ogrenmek için
print(random.shape)

(10,)


In [33]:
#boyutu düzenle
random.reshape((2,5))

array([[ 0, 42, 91, 19, 73],
       [88, 79, 27, 43, 38]])

In [36]:
#0 dan 100 e kadar sayıları 10a 10luk matris oluşturarak yazdırma
mat= np.arange(0,100).reshape(10,10)
print(mat)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [37]:
#belli bir satır sutundaki sayıya ulasma
mat[3,5]

35

In [44]:
#seçilen satırdaki elemanların hepsi
mat[:,5]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [41]:
#seçilen sütundaki elemanların hepsi
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [42]:
#seçilen sütundaki elemanların hepsini al alt alta yaz
mat[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [45]:
# iki sütun arasında istenen değeri alma
mat[0:2,0:2]

array([[ 0,  1],
       [10, 11]])

In [46]:
mat[0:4,0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

In [47]:
mat[0:4,0:4].shape

(4, 4)

In [49]:
#kopyasını oluştur
copy= mat.copy()
print(copy)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
